No Modulefiles Currently Loaded.
Running job on Hoffman2 with Job ID: 7659244
Python 3.9.6 and Anaconda3 2023.03 modules loaded
Conda environment activated successfully
Using Python from: /u/project/tpresner/shared/mypython/bin/python
Python 3.9.21
Flask server started with PID 15250
Failed to save response: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /hello (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2ad04ae79370>: Failed to establish a new connection: [Errno 111] Connection refused'))
Client script executed. Output saved to /u/project/tpresner/shared/qsub/practice/exercise2_tangai.txt
 * Serving Flask app 'flask_server'
 * Debug mode: off
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
